#' @import data.table
#' @export assmis
#' @export lrecode
#' @export savepdf
#' @export lookvar
#' @export formulas
#' @export revscale
#' @export Mean
#' @export Sd
#' @export Sum
#' @export Sums
#' @export Max
#' @export Min
#' @export factors
#' @export numerics
#' @export outliers
#' @export KnitPost
#' @export countmis
#' @export parmice
#' @export rowscore
#' @export uci
#' @export lci
#' @export getdummies
#' @export mi
#' @export mi_indicator
NULL
